version: '3.7'
services:
  mongodb:
    image: mongo:latest
    container_name: MongoDB
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_DB_USER:-root}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_DB_PASSWORD:-root}
    ports:
      - ${MONGO_DB_PORT:-27017}:27017
    volumes:
      - ./mongodb4:/data/db
volumes:
  mongodb4:
